### ISSUE TITLE
so node_redis doesn't have a pipeline option?

### ISSUE THREAD

**Issue by ORESoftware** [poppinlp/node_redis-vs-ioredis#4]
node_redis is faster, except when using pipeline with ioredis?
what is the pipeline about? have a link?

**Comment by poppinlp** [comment]
@ORESoftware Hi.
About the pipeline. It's a feature of Redis. You may take a look at [this document](https://redis.io/topics/pipelining).
And for node_redis, actually, there is a `batch` API. Seems I forgot to put it into the benchmarks. That's my fault. I may add it recently and PR is welcomed also. :)

**Comment by poppinlp** [comment]
I've updated the benchmark scripts and result already and gonna close this issue first. Feel free to reopen it if there's any further issues.
